spring:
  profiles:
    active: prod
  thymeleaf:
      cache : false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/creditindex?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    url: jdbc:mysql://cidri_app1:3306/idridb?autoReconnect=true&useSSL=false&characterEncoding=utf-8&useOldAliasMetadataBehavior=true
    username: idri
    password: Password01!
#    password: Mysql*ying13
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
#日志配置log\
logging:
  level:
    com.zy.creditindex: debug
    org.springfromework.web: info
    org.hibernate: error
  file: log\springboot.log
